[2024-08-21T20:43:57.366+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-21T20:43:57.388+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 3_models_dag_home.train_rf manual__2024-08-21T15:43:37.777131+00:00 [queued]>
[2024-08-21T20:43:57.396+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 3_models_dag_home.train_rf manual__2024-08-21T15:43:37.777131+00:00 [queued]>
[2024-08-21T20:43:57.397+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-21T20:43:57.409+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): train_rf> on 2024-08-21 15:43:37.777131+00:00
[2024-08-21T20:43:57.423+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=302430) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T20:43:57.424+0500] {standard_task_runner.py:72} INFO - Started process 302503 to run task
[2024-08-21T20:43:57.423+0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '3_models_dag_home', 'train_rf', 'manual__2024-08-21T15:43:37.777131+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/homework_stepik-checkpoint.py', '--cfg-path', '/tmp/tmphwmdk26t']
[2024-08-21T20:43:57.425+0500] {standard_task_runner.py:105} INFO - Job 173: Subtask train_rf
[2024-08-21T20:43:57.484+0500] {task_command.py:467} INFO - Running <TaskInstance: 3_models_dag_home.train_rf manual__2024-08-21T15:43:37.777131+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-08-21T20:43:57.565+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='3_models_dag_home' AIRFLOW_CTX_TASK_ID='train_rf' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T15:43:37.777131+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T15:43:37.777131+00:00'
[2024-08-21T20:43:57.566+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-21T20:43:57.605+0500] {s3.py:1387} INFO - Downloading source S3 file from Bucket test-bucket-nicolas-1 with path dataset/X_train.pkl
[2024-08-21T20:43:57.792+0500] {base.py:84} INFO - Retrieving connection 'aws_default'
[2024-08-21T20:43:57.793+0500] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-08-21T20:44:01.062+0500] {s3.py:1387} INFO - Downloading source S3 file from Bucket test-bucket-nicolas-1 with path dataset/X_test.pkl
[2024-08-21T20:44:01.755+0500] {s3.py:1387} INFO - Downloading source S3 file from Bucket test-bucket-nicolas-1 with path dataset/y_train.pkl
[2024-08-21T20:44:02.549+0500] {s3.py:1387} INFO - Downloading source S3 file from Bucket test-bucket-nicolas-1 with path dataset/y_test.pkl
[2024-08-21T20:44:02.986+0500] {homework_stepik-checkpoint.py:216} INFO - Данные загружены
[2024-08-21T20:44:03.111+0500] {migration.py:216} INFO - Context impl PostgresqlImpl.
[2024-08-21T20:44:03.111+0500] {migration.py:219} INFO - Will assume transactional DDL.
[2024-08-21T20:44:14.406+0500] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/airflow/dags/.ipynb_checkpoints/homework_stepik-checkpoint.py", line 221, in train_model
    train_mlflow_model(models[m_name], m_name, data["X_train"], data["X_test"], data["y_train"], data["y_test"],metrics)
  File "/home/nicolaspc/airflow/dags/.ipynb_checkpoints/homework_stepik-checkpoint.py", line 174, in train_mlflow_model
    prediction = model.predict(data["X_test"])
                               ^^^^
NameError: name 'data' is not defined
[2024-08-21T20:44:14.418+0500] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=3_models_dag_home, task_id=train_rf, run_id=manual__2024-08-21T15:43:37.777131+00:00, execution_date=20240821T154337, start_date=20240821T154357, end_date=20240821T154414
[2024-08-21T20:44:14.428+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-21T20:44:14.429+0500] {standard_task_runner.py:124} ERROR - Failed to execute job 173 for task train_rf (name 'data' is not defined; 302503)
Traceback (most recent call last):
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/airflow/dags/.ipynb_checkpoints/homework_stepik-checkpoint.py", line 221, in train_model
    train_mlflow_model(models[m_name], m_name, data["X_train"], data["X_test"], data["y_train"], data["y_test"],metrics)
  File "/home/nicolaspc/airflow/dags/.ipynb_checkpoints/homework_stepik-checkpoint.py", line 174, in train_mlflow_model
    prediction = model.predict(data["X_test"])
                               ^^^^
NameError: name 'data' is not defined
[2024-08-21T20:44:14.486+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-21T20:44:14.503+0500] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-21T20:44:14.506+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
