[2024-08-19T17:52:26.150+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-19T17:52:26.167+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 3_models_dag.save_results manual__2024-08-19T12:51:58.751130+00:00 [queued]>
[2024-08-19T17:52:26.175+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 3_models_dag.save_results manual__2024-08-19T12:51:58.751130+00:00 [queued]>
[2024-08-19T17:52:26.175+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-19T17:52:26.186+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): save_results> on 2024-08-19 12:51:58.751130+00:00
[2024-08-19T17:52:26.198+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=21461) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-19T17:52:26.198+0500] {standard_task_runner.py:72} INFO - Started process 21484 to run task
[2024-08-19T17:52:26.199+0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '3_models_dag', 'save_results', 'manual__2024-08-19T12:51:58.751130+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/train_models-2-checkpoint.py', '--cfg-path', '/tmp/tmpeu8y6kxa']
[2024-08-19T17:52:26.200+0500] {standard_task_runner.py:105} INFO - Job 41: Subtask save_results
[2024-08-19T17:52:26.250+0500] {task_command.py:467} INFO - Running <TaskInstance: 3_models_dag.save_results manual__2024-08-19T12:51:58.751130+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-08-19T17:52:26.336+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='3_models_dag' AIRFLOW_CTX_TASK_ID='save_results' AIRFLOW_CTX_EXECUTION_DATE='2024-08-19T12:51:58.751130+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-19T12:51:58.751130+00:00'
[2024-08-19T17:52:26.337+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-19T17:52:26.363+0500] {base.py:84} INFO - Retrieving connection 'aws_default'
[2024-08-19T17:52:26.382+0500] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-08-19T17:52:27.255+0500] {python.py:240} INFO - Done. Returned value was: None
[2024-08-19T17:52:27.268+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-19T17:52:27.268+0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=3_models_dag, task_id=save_results, run_id=manual__2024-08-19T12:51:58.751130+00:00, execution_date=20240819T125158, start_date=20240819T125226, end_date=20240819T125227
[2024-08-19T17:52:27.296+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-19T17:52:27.313+0500] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-19T17:52:27.316+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
