[2024-10-08T18:58:58.004+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T18:58:58.020+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hgb_train.train_model manual__2024-10-08T13:58:28.824824+00:00 [queued]>
[2024-10-08T18:58:58.027+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hgb_train.train_model manual__2024-10-08T13:58:28.824824+00:00 [queued]>
[2024-10-08T18:58:58.028+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-10-08T18:58:58.039+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): train_model> on 2024-10-08 13:58:28.824824+00:00
[2024-10-08T18:58:58.051+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=242395) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-08T18:58:58.052+0500] {standard_task_runner.py:72} INFO - Started process 242440 to run task
[2024-10-08T18:58:58.052+0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'hgb_train', 'train_model', 'manual__2024-10-08T13:58:28.824824+00:00', '--job-id', '752', '--raw', '--subdir', 'DAGS_FOLDER/train_models.py', '--cfg-path', '/tmp/tmphhwureau']
[2024-10-08T18:58:58.054+0500] {standard_task_runner.py:105} INFO - Job 752: Subtask train_model
[2024-10-08T18:58:58.106+0500] {task_command.py:467} INFO - Running <TaskInstance: hgb_train.train_model manual__2024-10-08T13:58:28.824824+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-10-08T18:58:58.186+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='hgb_train' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T13:58:28.824824+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T13:58:28.824824+00:00'
[2024-10-08T18:58:58.187+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T18:58:58.360+0500] {s3.py:1387} INFO - Downloading source S3 file from Bucket test-bucket-nicolas-1 with path NicolasPal/project1/hgb/datasets/X_train.pkl
[2024-10-08T18:58:58.373+0500] {base.py:84} INFO - Retrieving connection 's3_connection'
[2024-10-08T18:58:58.373+0500] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-08T18:59:05.071+0500] {s3.py:1387} INFO - Downloading source S3 file from Bucket test-bucket-nicolas-1 with path NicolasPal/project1/hgb/datasets/X_test.pkl
[2024-10-08T18:59:05.517+0500] {s3.py:1387} INFO - Downloading source S3 file from Bucket test-bucket-nicolas-1 with path NicolasPal/project1/hgb/datasets/y_train.pkl
[2024-10-08T18:59:05.975+0500] {s3.py:1387} INFO - Downloading source S3 file from Bucket test-bucket-nicolas-1 with path NicolasPal/project1/hgb/datasets/y_test.pkl
[2024-10-08T18:59:06.434+0500] {train_models.py:184} INFO - Данные для обучения модели из S3 загружены
[2024-10-08T18:59:06.536+0500] {migration.py:216} INFO - Context impl PostgresqlImpl.
[2024-10-08T18:59:06.536+0500] {migration.py:219} INFO - Will assume transactional DDL.
[2024-10-08T18:59:10.146+0500] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-10-08T18:59:21.431+0500] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/airflow/dags/train_models.py", line 214, in train_model
    mlflow.evaluate(
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/models/evaluation/base.py", line 2106, in evaluate
    data = _convert_data_to_mlflow_dataset(data=data, targets=targets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/models/evaluation/base.py", line 1236, in _convert_data_to_mlflow_dataset
    return mlflow.data.from_numpy(data, targets=targets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/data/numpy_dataset.py", line 219, in from_numpy
    return NumpyDataset(
           ^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/data/numpy_dataset.py", line 45, in __init__
    super().__init__(source=source, name=name, digest=digest)
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/data/dataset.py", line 27, in __init__
    self._digest = digest or self._compute_digest()
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/data/numpy_dataset.py", line 52, in _compute_digest
    return compute_numpy_digest(self._features, self._targets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/data/digest_utils.py", line 83, in compute_numpy_digest
    hash_array(item)
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/data/digest_utils.py", line 62, in hash_array
    flattened_array = array.flatten()
                      ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'flatten'
[2024-10-08T18:59:21.457+0500] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=hgb_train, task_id=train_model, run_id=manual__2024-10-08T13:58:28.824824+00:00, execution_date=20241008T135828, start_date=20241008T135858, end_date=20241008T135921
[2024-10-08T18:59:21.631+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T18:59:21.632+0500] {standard_task_runner.py:124} ERROR - Failed to execute job 752 for task train_model ('str' object has no attribute 'flatten'; 242440)
Traceback (most recent call last):
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/airflow/dags/train_models.py", line 214, in train_model
    mlflow.evaluate(
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/models/evaluation/base.py", line 2106, in evaluate
    data = _convert_data_to_mlflow_dataset(data=data, targets=targets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/models/evaluation/base.py", line 1236, in _convert_data_to_mlflow_dataset
    return mlflow.data.from_numpy(data, targets=targets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/data/numpy_dataset.py", line 219, in from_numpy
    return NumpyDataset(
           ^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/data/numpy_dataset.py", line 45, in __init__
    super().__init__(source=source, name=name, digest=digest)
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/data/dataset.py", line 27, in __init__
    self._digest = digest or self._compute_digest()
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/data/numpy_dataset.py", line 52, in _compute_digest
    return compute_numpy_digest(self._features, self._targets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/data/digest_utils.py", line 83, in compute_numpy_digest
    hash_array(item)
  File "/home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/mlflow/data/digest_utils.py", line 62, in hash_array
    flattened_array = array.flatten()
                      ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'flatten'
[2024-10-08T18:59:21.692+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-10-08T18:59:21.710+0500] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T18:59:21.857+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
