[2024-08-21T21:35:13.602+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-21T21:35:13.623+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 3_models_dag_home.get_data manual__2024-08-21T16:35:10.013981+00:00 [queued]>
[2024-08-21T21:35:13.632+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 3_models_dag_home.get_data manual__2024-08-21T16:35:10.013981+00:00 [queued]>
[2024-08-21T21:35:13.632+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-21T21:35:13.644+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_data> on 2024-08-21 16:35:10.013981+00:00
[2024-08-21T21:35:13.661+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/anaconda3/envs/mlops_env/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=325771) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-21T21:35:13.663+0500] {standard_task_runner.py:72} INFO - Started process 325795 to run task
[2024-08-21T21:35:13.661+0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '3_models_dag_home', 'get_data', 'manual__2024-08-21T16:35:10.013981+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/homework_stepik-checkpoint.py', '--cfg-path', '/tmp/tmpikspnnrv']
[2024-08-21T21:35:13.665+0500] {standard_task_runner.py:105} INFO - Job 198: Subtask get_data
[2024-08-21T21:35:13.721+0500] {task_command.py:467} INFO - Running <TaskInstance: 3_models_dag_home.get_data manual__2024-08-21T16:35:10.013981+00:00 [running]> on host nicolaspc-HP-Pavilion-Laptop-15-eh1xxx
[2024-08-21T21:35:13.805+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nicolas Pal' AIRFLOW_CTX_DAG_ID='3_models_dag_home' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T16:35:10.013981+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T16:35:10.013981+00:00'
[2024-08-21T21:35:13.806+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-21T21:35:14.004+0500] {base.py:84} INFO - Retrieving connection 'pg_connection'
[2024-08-21T21:35:14.017+0500] {logging_mixin.py:190} WARNING - /home/nicolaspc/***/dags/.ipynb_checkpoints/homework_stepik-checkpoint.py:91 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-08-21T21:35:14.109+0500] {base.py:84} INFO - Retrieving connection 'aws_default'
[2024-08-21T21:35:14.110+0500] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-08-21T21:35:22.833+0500] {homework_stepik-checkpoint.py:102} INFO - Data download finished.
[2024-08-21T21:35:22.835+0500] {python.py:240} INFO - Done. Returned value was: {'start_tiemstamp': '20240821 21:35', 'data_download_start': '20240821 21:35', 'data_download_end': '20240821 21:35'}
[2024-08-21T21:35:22.866+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-21T21:35:22.866+0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=3_models_dag_home, task_id=get_data, run_id=manual__2024-08-21T16:35:10.013981+00:00, execution_date=20240821T163510, start_date=20240821T163513, end_date=20240821T163522
[2024-08-21T21:35:22.931+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-21T21:35:22.954+0500] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-21T21:35:22.957+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
